services:
  app:
    build:
      context: ../
      dockerfile: docker/dockerfile
    container_name: go-task-service
    ports:
      - "8080:8080"
    volumes:
      - ..:/app
      - air-config:/root/.air
    env_file:
      - ../.env
    networks:
      - shared_network

volumes:
  air-config:
  pgdata:

networks:
  shared_network:
    external: true

